name: Publish Developer Version
on:
  release:
    types: [created]
jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Login into NPM
        run: npm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
        
      - name: Install Latest npm
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: npm install
        
      - name: Build the Package
        run: npm run build
      
      - name: Change Version to ${{ github.event.release.tag_name }}
        run: npm version --git-tag-version=false ${{ github.event.release.tag_name }}
        
      - name: Publish
        run: npm run publish --tag dev
